---
defaults:
  email_sender: Compose Alert <compose-alert@centos.org>
  email_to:
    - centos-stream-releng@redhat.com
  alert_days: 3

composes:
  - description: Fedora ELN Compose
    url: https://odcs.fedoraproject.org/composes/production
    name: Fedora-ELN
    version: Rawhide
